
-- Generated by ORDS REST Data Services 26.2.0.r1732140
-- Schema: WKSP_ARCHI04  Date: Tue Sep 22 12:29:20 2026 
--
        
DECLARE

  l_roles     OWA.VC_ARR;
  l_modules   OWA.VC_ARR;
  l_patterns  OWA.VC_ARR;

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'archi_04',
      p_auto_rest_auth      => FALSE);

  ORDS.DEFINE_MODULE(
      p_module_name    => 'DELETE Method',
      p_base_path      => '/login/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'DELETE Method',
      p_pattern        => 'users/:USER_ID',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'DELETE Method',
      p_pattern        => 'users/:USER_ID',
      p_method         => 'DELETE',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
    v_user_id NUMBER;
BEGIN

    -- Get USER_ID from URL
    v_user_id := :USER_ID;

    -- Validate USER_ID
    IF v_user_id IS NULL THEN

        :status_code := 400;

        APEX_JSON.OPEN_OBJECT;
        APEX_JSON.WRITE(''status'', ''error'');
        APEX_JSON.WRITE(''message'', ''USER_ID is required'');
        APEX_JSON.CLOSE_OBJECT;

        RETURN;
    END IF;

    -- Delete user
    DELETE FROM TA_USER
    WHERE USER_ID = v_user_id;

    IF SQL%ROWCOUNT > 0 THEN

        COMMIT;

        :status_code := 200;

        APEX_JSON.OPEN_OBJECT;
        APEX_JSON.WRITE(''status'', ''success'');
        APEX_JSON.WRITE(''message'', ''User deleted successfully'');
        APEX_JSON.WRITE(''deleted_user_id'', v_user_id);
        APEX_JSON.CLOSE_OBJECT;

    ELSE

        ROLLBACK;

        :status_code := 404;

        APEX_JSON.OPEN_OBJECT;
        APEX_JSON.WRITE(''status'', ''error'');
        APEX_JSON.WRITE(''message'', ''No user found with the provide' || 'd USER_ID'');
        APEX_JSON.WRITE(''user_id'', v_user_id);
        APEX_JSON.CLOSE_OBJECT;

    END IF;

EXCEPTION
    WHEN OTHERS THEN

        ROLLBACK;

        :status_code := 500;

        APEX_JSON.OPEN_OBJECT;
        APEX_JSON.WRITE(''status'', ''error'');
        APEX_JSON.WRITE(''message'', SQLERRM);
        APEX_JSON.CLOSE_OBJECT;

END;');

COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;

END;