
-- Generated by ORDS REST Data Services 26.2.0.r1732140
-- Schema: WKSP_ARCHI04  Date: Tue Sep 22 12:16:10 2026 
--
        
DECLARE

  l_roles     OWA.VC_ARR;
  l_modules   OWA.VC_ARR;
  l_patterns  OWA.VC_ARR;

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'archi_04',
      p_auto_rest_auth      => FALSE);

  ORDS.DEFINE_MODULE(
      p_module_name    => 'Get All Data',
      p_base_path      => '/meetings/',
      p_items_per_page => 50,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'Get All Data',
      p_pattern        => 'data',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'Get All Data',
      p_pattern        => 'data',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'-- without filter 

-- select * from TA_MEETINGS

SELECT *
FROM TA_MEETINGS
WHERE (:title IS NULL
       OR MEETING_TITLE LIKE ''%'' || :title || ''%'')
AND (:organizer IS NULL
     OR ORGANIZER_ID = :organizer)
AND (:status IS NULL
     OR UPPER(STATUS) = UPPER(:status))
ORDER BY MEETING_ID DESC');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'Get All Data',
      p_pattern            => 'data',
      p_method             => 'GET',
      p_name               => 'organizer',
      p_bind_variable_name => 'organizer',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'Get All Data',
      p_pattern            => 'data',
      p_method             => 'GET',
      p_name               => 'status',
      p_bind_variable_name => 'status',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'Get All Data',
      p_pattern            => 'data',
      p_method             => 'GET',
      p_name               => 'title',
      p_bind_variable_name => 'title',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;

END;