
-- Generated by ORDS REST Data Services 26.2.0.r1732140
-- Schema: WKSP_ARCHI04  Date: Tue Sep 22 12:28:37 2026 
--
        
DECLARE

  l_roles     OWA.VC_ARR;
  l_modules   OWA.VC_ARR;
  l_patterns  OWA.VC_ARR;

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'archi_04',
      p_auto_rest_auth      => FALSE);

  ORDS.DEFINE_MODULE(
      p_module_name    => 'PUT Method',
      p_base_path      => '/users/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'PUT Method',
      p_pattern        => ':id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'PUT Method',
      p_pattern        => ':id',
      p_method         => 'PUT',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
    l_body_blob BLOB;
    l_json_obj  JSON_OBJECT_T;
    l_username  VARCHAR2(255);
    l_password  VARCHAR2(255);
BEGIN
    -- 1. Read the raw HTTP request body payload
    l_body_blob := :body;
    
    -- 2. Parse the payload into a native JSON object
    l_json_obj := JSON_OBJECT_T.parse(l_body_blob);
    
    -- 3. Extract the properties sent by the API client
    l_username := l_json_obj.get_string(''username'');
    l_password := l_json_obj.get_string(''password'');

    -- 4. Execute the update using the path parameter (:id)
    -- Note: Your trigger handles the UPDATED and UPDATED_BY audits automatically!
    UPDATE ta_user
       SET username = NVL(l_username, username),
           password = NVL(l_password, password)
     WHERE user_id  = :id;

    -- 5. Send back the correct HTTP response status code
    IF SQL%ROWCOUNT = 0 THEN
        :status_code := 404; -- Not Found
    ELSE
        :status_code := 200; -- OK / Updated
    END IF;

EXCE' || 'PTION
    WHEN OTHERS THEN
        -- Safely handle validation or unique constraint errors (e.g., duplicate username)
        :status_code := 400; 
END;
');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'PUT Method',
      p_pattern            => ':id',
      p_method             => 'PUT',
      p_name               => 'X-ORDS-STATUS-CODE',
      p_bind_variable_name => 'status_code',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);

COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;

END;