
-- Generated by ORDS REST Data Services 26.2.0.r1732140
-- Schema: WKSP_ARCHI04  Date: Tue Sep 22 12:27:29 2026 
--
        
DECLARE

  l_roles     OWA.VC_ARR;
  l_modules   OWA.VC_ARR;
  l_patterns  OWA.VC_ARR;

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'archi_04',
      p_auto_rest_auth      => FALSE);

  ORDS.DEFINE_MODULE(
      p_module_name    => 'POST method',
      p_base_path      => '/user/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'POST method',
      p_pattern        => 'data/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'POST method',
      p_pattern        => 'data/',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
    j_obj       JSON_OBJECT_T;
    v_password  VARCHAR2(100);
    v_username  VARCHAR2(100);
BEGIN

    -- Parse JSON body
    j_obj := JSON_OBJECT_T.parse(:body);

    -- Get values from JSON
    v_username := j_obj.get_String(''username'');
    v_password := j_obj.get_String(''password'');

    -- Insert user
    INSERT INTO TA_USER (
        USERNAME,
        PASSWORD
    )
    VALUES (
        v_username,
        v_password
    );

    COMMIT;

END;');

COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;

END;