
-- Generated by ORDS REST Data Services 26.2.0.r1732140
-- Schema: WKSP_ARCHI04  Date: Tue Sep 22 12:25:14 2026 
--
        
DECLARE

  l_roles     OWA.VC_ARR;
  l_modules   OWA.VC_ARR;
  l_patterns  OWA.VC_ARR;

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'archi_04',
      p_auto_rest_auth      => FALSE);

  ORDS.DEFINE_MODULE(
      p_module_name    => 'property',
      p_base_path      => '/property/',
      p_items_per_page => 10000,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'property',
      p_pattern        => 'get',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'property',
      p_pattern        => 'get',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT * FROM PMS_PROPERTY_MASTER
WHERE 
(:PROPERTY_ID IS NULL
OR PROPERTY_ID = :PROPERTY_ID)
AND
(:PROPERTY_TYPE IS NULL
OR PROPERTY_TYPE = :PROPERTY_TYPE)
AND 
(:PROPERTY_AVAILABILITY_STATUS IS NULL
OR PROPERTY_AVAILABILITY_STATUS = :PROPERTY_AVAILABILITY_STATUS)');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'property',
      p_pattern            => 'get',
      p_method             => 'GET',
      p_name               => 'PROPERTY_ID',
      p_bind_variable_name => 'PROPERTY_ID',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'property',
      p_pattern            => 'get',
      p_method             => 'GET',
      p_name               => 'PROPERTY_TYPE',
      p_bind_variable_name => 'PROPERTY_TYPE',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'property',
      p_pattern            => 'get',
      p_method             => 'GET',
      p_name               => 'PROPERTY_AVAILABILITY_STATUS',
      p_bind_variable_name => 'PROPERTY_AVAILABILITY_STATUS',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;

END;