ALTER TABLE "XXPI_NAVIGATION_MENU_MASTER" ADD CONSTRAINT "XXPI_NAVIGATION_MENU_MASTER_CON_PARENT_MENU_ID_FK" FOREIGN KEY ("PARENT_MENU_ID")
	  REFERENCES "XXPI_NAVIGATION_MENU_MASTER" ("MENU_ID") DISABLE;
