create or replace FUNCTION TA_CUSTOM_AUTH(
    P_USERNAME IN VARCHAR2,
    P_PASSWORD IN VARCHAR2
) RETURN BOOLEAN
IS
    V_COUNT NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_COUNT 
    FROM TA_USER
    WHERE UPPER(USERNAME) = UPPER(P_USERNAME)
    AND PASSWORD = P_PASSWORD;

    RETURN V_COUNT > 0;
END;
/