create or replace TRIGGER "TA_DAYWISE_NAVIGATION_MENU_MASTER_BIU" 
BEFORE INSERT OR UPDATE ON TA_DAYWISE_NAVIGATION_MENU_MASTER
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATED := SYSDATE;
        :NEW.CREATED_BY := NVL(V('APP_USER'), USER);
    END IF;

    IF UPDATING THEN
        :NEW.UPDATED := SYSDATE;
        :NEW.UPDATED_BY := NVL(V('APP_USER'), USER);
    END IF;
END;
/