create or replace TRIGGER "TA_EMP_BIU" 
BEFORE INSERT OR UPDATE ON TA_EMP
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATED_ON := SYSDATE;
        :NEW.CREATED_BY := NVL(V('APP_USER'), USER);
    END IF;

    IF UPDATING THEN
        :NEW.UPDATED_ON := SYSDATE;
        :NEW.UPDATED_BY := NVL(V('APP_USER'), USER);
    END IF;
END;
/