create or replace TRIGGER "TA_USER_ACTIVITY_LOGS_BIU" 
BEFORE INSERT OR UPDATE ON "TA_USER_ACTIVITY_LOGS"
FOR EACH ROW
BEGIN
  IF INSERTING THEN
    :NEW.created_at := SYSTIMESTAMP;
    :NEW.created_by := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
  END IF;

  IF UPDATING THEN
    :NEW.updated_at := SYSTIMESTAMP;
    :NEW.updated_by := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
  END IF;
END TA_USER_ACTIVITY_LOGS_BIU;
/