  CREATE TABLE "EBA_DEMO_MD_TASK_TODOS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"PROJECT_ID" NUMBER NOT NULL ENABLE, 
	"TASK_ID" NUMBER NOT NULL ENABLE, 
	"ASSIGNEE" NUMBER, 
	"NAME" VARCHAR2(255) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(4000), 
	"IS_COMPLETE_YN" VARCHAR2(1), 
	"CREATED" TIMESTAMP (6) WITH TIME ZONE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	"UPDATED" TIMESTAMP (6) WITH TIME ZONE NOT NULL ENABLE, 
	"UPDATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	 CONSTRAINT "EBA_DEMO_MD_TASK_TODOS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "EBA_DEMO_MD_TASK_TODOS" ADD CONSTRAINT "EBA_DEMO_MD_TASK_TODO_PRJ_FK" FOREIGN KEY ("PROJECT_ID")
	  REFERENCES "EBA_DEMO_MD_PROJECTS" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "EBA_DEMO_MD_TASK_TODOS" ADD CONSTRAINT "EBA_DEMO_MD_TASK_TODO_TM_FK" FOREIGN KEY ("ASSIGNEE")
	  REFERENCES "EBA_DEMO_MD_TEAM_MEMBERS" ("ID") ON DELETE SET NULL ENABLE;
  ALTER TABLE "EBA_DEMO_MD_TASK_TODOS" ADD CONSTRAINT "EBA_DEMO_MD_TASK_TODO_TSK_FK" FOREIGN KEY ("TASK_ID")
	  REFERENCES "EBA_DEMO_MD_TASKS" ("ID") ON DELETE CASCADE ENABLE;

  CREATE INDEX "EBA_DEMO_MD_TSK_TODO_PRJ_IDX" ON "EBA_DEMO_MD_TASK_TODOS" ("PROJECT_ID") 
  ;

  CREATE INDEX "EBA_DEMO_MD_TASK_TODO_TM_IDX" ON "EBA_DEMO_MD_TASK_TODOS" ("ASSIGNEE") 
  ;

  CREATE INDEX "EBA_DEMO_MD_TSK_TODO_TSK_IDX" ON "EBA_DEMO_MD_TASK_TODOS" ("TASK_ID") 
  ;