  CREATE TABLE "EBA_DEMO_MD_COMMENTS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"PROJECT_ID" NUMBER NOT NULL ENABLE, 
	"COMMENT_TEXT" VARCHAR2(4000) NOT NULL ENABLE, 
	"CREATED" TIMESTAMP (6) WITH TIME ZONE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	"UPDATED" TIMESTAMP (6) WITH TIME ZONE NOT NULL ENABLE, 
	"UPDATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	 CONSTRAINT "EBA_DEMO_MD_COMMENTS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "EBA_DEMO_MD_COMMENTS" ADD CONSTRAINT "EBA_DEMO_MD_COMMENT_MD_FK" FOREIGN KEY ("PROJECT_ID")
	  REFERENCES "EBA_DEMO_MD_PROJECTS" ("ID") ON DELETE CASCADE ENABLE;

  CREATE INDEX "EBA_DEMO_MD_COMMENT_MD_IDX" ON "EBA_DEMO_MD_COMMENTS" ("PROJECT_ID") 
  ;