  CREATE TABLE "EBA_DEMO_MD_TASKS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"PROJECT_ID" NUMBER NOT NULL ENABLE, 
	"MILESTONE_ID" NUMBER, 
	"ASSIGNEE" NUMBER, 
	"NAME" VARCHAR2(255) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(4000), 
	"START_DATE" DATE NOT NULL ENABLE, 
	"END_DATE" DATE NOT NULL ENABLE, 
	"IS_COMPLETE_YN" VARCHAR2(1), 
	"CREATED" TIMESTAMP (6) WITH TIME ZONE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	"UPDATED" TIMESTAMP (6) WITH TIME ZONE NOT NULL ENABLE, 
	"UPDATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	 CONSTRAINT "EBA_DEMO_MD_TASKS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "EBA_DEMO_MD_TASKS_UK" UNIQUE ("PROJECT_ID", "NAME")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "EBA_DEMO_MD_TASKS" ADD CONSTRAINT "EBA_DEMO_MD_TASK_MSTONE_FK" FOREIGN KEY ("MILESTONE_ID")
	  REFERENCES "EBA_DEMO_MD_MILESTONES" ("ID") ON DELETE SET NULL ENABLE;
  ALTER TABLE "EBA_DEMO_MD_TASKS" ADD CONSTRAINT "EBA_DEMO_MD_TASK_PROJECT_FK" FOREIGN KEY ("PROJECT_ID")
	  REFERENCES "EBA_DEMO_MD_PROJECTS" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "EBA_DEMO_MD_TASKS" ADD CONSTRAINT "EBA_DEMO_MD_TASK_TEAM_MEM_FK" FOREIGN KEY ("ASSIGNEE")
	  REFERENCES "EBA_DEMO_MD_TEAM_MEMBERS" ("ID") ON DELETE SET NULL ENABLE;

  CREATE INDEX "EBA_DEMO_MD_TASK_PROJECT_IDX" ON "EBA_DEMO_MD_TASKS" ("PROJECT_ID") 
  ;

  CREATE INDEX "EBA_DEMO_MD_TASK_MSTONE_IDX" ON "EBA_DEMO_MD_TASKS" ("MILESTONE_ID") 
  ;

  CREATE INDEX "EBA_DEMO_MD_TASK_TEAM_MM_IDX" ON "EBA_DEMO_MD_TASKS" ("ASSIGNEE") 
  ;