  CREATE TABLE "EBA_UT_MAP_AIRPORTS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"IATA_CODE" VARCHAR2(10), 
	"AIRPORT_TYPE" VARCHAR2(255), 
	"AIRPORT_NAME" VARCHAR2(255), 
	"CITY" VARCHAR2(255), 
	"STATE_NAME" VARCHAR2(255), 
	"ACTIVATION_DATE" VARCHAR2(50), 
	"ACTIVATION_DATE_DT" DATE, 
	"ELEVATION" NUMBER, 
	"DIST_CITY_TO_AIRPORT" NUMBER, 
	"LAND_AREA_COVERED" NUMBER, 
	"COMMERCIAL_OPS" NUMBER, 
	"AIR_TAXI_OPS" NUMBER, 
	"GEOMETRY" "MDSYS"."SDO_GEOMETRY" , 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) 
 VARRAY "GEOMETRY"."SDO_ELEM_INFO" STORE AS SECUREFILE LOB 
 VARRAY "GEOMETRY"."SDO_ORDINATES" STORE AS SECUREFILE LOB ;