  CREATE TABLE "EBA_UT_CHART_TASKS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"PROJECT" NUMBER, 
	"PARENT_TASK" NUMBER, 
	"TASK_NAME" VARCHAR2(255), 
	"ROW_VERSION_NUMBER" NUMBER, 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"STATUS" VARCHAR2(30), 
	"ASSIGNED_TO" VARCHAR2(30), 
	"COST" NUMBER, 
	"BUDGET" NUMBER, 
	"CREATED" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(255), 
	"UPDATED" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(255), 
	 CONSTRAINT "EBA_UT_CHART_TASKS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "EBA_UT_CHART_TASKS" ADD CONSTRAINT "EBA_UT_CHART_TASKS_FK" FOREIGN KEY ("PROJECT")
	  REFERENCES "EBA_UT_CHART_PROJECTS" ("ID") ON DELETE CASCADE ENABLE;

  CREATE INDEX "EBA_UT_CHART_TASKS_IDX1" ON "EBA_UT_CHART_TASKS" ("PROJECT") 
  ;