  CREATE TABLE "SCM_STATE_BBOX" 
   (	"STATE_CODE" VARCHAR2(5), 
	"STATE_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"STATE_GEOM" "SDO_GEOMETRY", 
	 PRIMARY KEY ("STATE_CODE")
  USING INDEX  ENABLE
   ) 
 VARRAY "STATE_GEOM"."SDO_ELEM_INFO" STORE AS SECUREFILE LOB 
 VARRAY "STATE_GEOM"."SDO_ORDINATES" STORE AS SECUREFILE LOB ;