create or replace TRIGGER "DEMO_DATA_LOAD_BIU" 
BEFORE INSERT OR UPDATE ON DEMO_DATA_LOAD
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATED_AT := SYSDATE;
        :NEW.CREATED_BY := NVL(V('APP_USER'), USER);
    END IF;

    IF UPDATING THEN
        :NEW.UPDATED_AT := SYSDATE;
        :NEW.UPDATED_BY := NVL(V('APP_USER'), USER);
    END IF;
END;
/