create or replace TRIGGER "TA_USER_BIU" 
BEFORE INSERT OR UPDATE ON TA_USER
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATED := SYSDATE;
        :NEW.CREATED_BY := NVL(V('APP_USER'), USER);
    END IF;

        :NEW.UPDATED := SYSDATE;
        :NEW.UPDATED_BY := NVL(V('APP_USER'), USER);
END;
/