create or replace TRIGGER "TRG_LETTER_TEMPLATE_AUDIT" 
BEFORE INSERT OR UPDATE
ON AOP_DEMO_LETTER_TEMPLATE_MASTER
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATED_ON := SYSDATE;
        :NEW.CREATED_BY := NVL(V('APP_USER'), USER);
    END IF;

    IF UPDATING THEN
        :NEW.UPDATED_ON := SYSDATE;
        :NEW.UPDATED_BY := NVL(V('APP_USER'), USER);
    END IF;
END;
/